default_platform(:ios)

platform :ios do
  desc 'Description of what the lane does'
  lane :certificates do
    sync_code_signing(
      app_identifier: 'com.ocelotgraphql.ios.app.debug',
      readonly: true
    )
    sync_code_signing(
      app_identifier: 'com.ocelotgraphql.ios.app',
      type: 'appstore',
      readonly: true
    )
  end
end
